reown-com/reown-docs

docs/components/WhatsNewBanner.js
docs/readme.mdx

We need a simple "What's New?" banner on the home page of the docs. This PR adds that. 
Tested locally with Docusauras.

Docs update: Adding a banner announcing that WalletConnect is now Reown

---

docs/appkit/react/wagmi/about/implementation.mdx

Fixes wrong docs on AppKit's wagmi adapter implementation
Reported on: https://github.com/orgs/WalletConnect/discussions/5372

fix: wagmiConfig documentation for appkit implementatino

---

docs/appkit/vue/core/composables.mdx
docs/appkit/vue/core/installation.mdx
docs/appkit/vue/ethers/composables.mdx
docs/appkit/vue/solana/programs.mdx

Update the Vue documentation that was using React.
Issue related : https://github.com/reown-com/appkit/issues/2869

Chore: Fix vue docs 

---

docs/advanced/multichain/polkadot/dapp-integration-guide.md
docs/advanced/multichain/polkadot/namespaces-guide.md
docs/advanced/multichain/rpc-reference/casper-rpc.md
docs/advanced/multichain/rpc-reference/hedera-rpc.md
docs/advanced/multichain/rpc-reference/near-rpc.md

Hello
I found and fixed several spelling issues in your docs.
Br, Elias.

docs: fix spelling issues

---

docusaurus.config.js

chore: Update link for github discussins

---

docs/appkit/javascript/core/installation.mdx
docs/appkit/migration/from-rainbowkit-next.mdx
docs/appkit/next/core/installation.mdx
docs/appkit/react/core/installation.mdx
docs/appkit/vue/core/installation.mdx

- Add @reown/appkit package to installation guide.
- Update Rainbowkit migration guide

fix: Add @reown/appkit package to installation guide.

---

docs/appkit/javascript/core/actions.mdx
docs/appkit/javascript/ethers5/implementation.mdx
docs/appkit/next/core/hooks.mdx
docs/appkit/next/ethers/about/implementation.mdx
docs/appkit/react/core/hooks.mdx
docs/appkit/react/ethers/about/implementation.mdx
docs/appkit/react/ethers5/implementation.mdx
docs/appkit/vue/core/composables.mdx
docs/appkit/vue/ethers/about/implementation.mdx
docs/appkit/vue/ethers5/implementation.mdx

+ Ethers v5 problem
+ Add swap to the open options

Fix: Ethesv5 problem

---

docs/appkit/features/socials.mdx
docs/appkit/next/ethers5/implementation.mdx

+ small fix in ethers v5
+ add solanas networks to social network supported

Fix: ethesv5 problem & social logins

---

docs/appkit/features/multichain.mdx
docs/appkit/shared/resources.mdx

fix: doc links

---

docs/appkit/react/wagmi/about/implementation.mdx

Use wagmiAdapter instead of WagmiAdapter in  adapters.

Fix wagmiAdapter spelling. Update implementation.mdx

---

docs/advanced/multichain/rpc-reference/solana-rpc.md

This PR is adding new methods for Solana RPC spec and updating the older ones.

chore: add solana_signAllTransactions solana_signAndSendTransaction and update older methods

---

docs/appkit/javascript/core/custom-connectors.mdx
docs/appkit/javascript/ethers/about/implementation.mdx
docs/appkit/javascript/ethers5/implementation.mdx
docs/appkit/javascript/solana/about/implementation.mdx
docs/appkit/javascript/wagmi/about/implementation.mdx
docs/appkit/next/ethers/about/implementation.mdx
docs/appkit/next/ethers5/implementation.mdx
docs/appkit/next/solana/about/implementation.mdx
docs/appkit/react/core/custom-connectors.mdx
docs/appkit/react/ethers/about/implementation.mdx
docs/appkit/react/ethers5/implementation.mdx
docs/appkit/react/solana/about/implementation.mdx
docs/appkit/react/wagmi/about/implementation.mdx
docs/appkit/shared/multichain.mdx
docs/appkit/upgrade/appkitv2.mdx
docs/appkit/upgrade/to-reown-appkit-web.mdx
docs/appkit/vue/ethers/about/implementation.mdx
docs/appkit/vue/ethers5/implementation.mdx
docs/appkit/vue/solana/about/implementation.mdx
docs/appkit/vue/solana/implementation.mdx
docs/appkit/vue/wagmi/about/implementation.mdx

Can check some modifications over: https://reown-docs-git-fix-several-fix-over-docs-reown-com.vercel.app/appkit/react/core/installation?platform=wagmi

fix: Several issues on docs

---

docs/appkit/javascript/core/custom-networks.mdx
docs/appkit/javascript/wagmi/about/implementation.mdx
docs/appkit/next/core/custom-networks.mdx
docs/appkit/next/wagmi/about/implementation.mdx
docs/appkit/react/core/custom-networks.mdx
docs/appkit/react/wagmi/about/implementation.mdx
docs/appkit/vue/core/custom-networks.mdx
docs/appkit/vue/wagmi/about/implementation.mdx

The previous PR that was merged which consisted information about configuring custom chains with AppKit and also how AppKit uses Viem under the hood had a few minor inconsistencies and grammar issues. This PR addresses those issues. 
Tested locally with Docusaurus

Docs update: Making grammar fixes and minor changes to custom chains and Wagmi implementation docs

---

docs/advanced/security/content-security-policy.md

Updates the CSP according to the latest tested version: https://github.com/WalletConnect/web3modal/pull/2775
Old PR: https://github.com/WalletConnect/walletconnect-docs/pull/1697

fix: update CSP

---

docs/appkit/javascript/solana/about/programs.mdx
docs/appkit/javascript/wagmi/about/implementation.mdx
docs/appkit/next/core/hooks.mdx
docs/appkit/next/core/installation.mdx
docs/appkit/next/core/open.mdx
docs/appkit/next/ethers/about/implementation.mdx
docs/appkit/next/ethers5/hooks.mdx
docs/appkit/next/ethers5/implementation.mdx
docs/appkit/next/solana/about/programs.mdx
docs/appkit/next/solana/hooks.mdx
docs/appkit/react-native/core/resources.mdx
docs/appkit/react/core/custom-connectors.mdx
docs/appkit/react/core/hooks.mdx
docs/appkit/react/core/open.mdx
docs/appkit/react/ethers/hooks.mdx
docs/appkit/react/solana/about/programs.mdx
docs/appkit/react/solana/hooks.mdx
docs/appkit/react/solana/implementation.mdx
docs/appkit/react/solana/triggermodal.mdx
docs/appkit/react/wagmi/hooks.mdx
docs/appkit/shared/smart-accounts.mdx
docs/appkit/vue/core/composables.mdx
docs/appkit/vue/core/custom-connectors.mdx
docs/appkit/vue/core/open.mdx
docs/appkit/vue/ethers/about/triggermodal.mdx
docs/appkit/vue/ethers5/triggermodal.mdx
docs/appkit/vue/solana/about/implementation.mdx
docs/appkit/vue/solana/programs.mdx
docs/appkit/vue/solana/triggermodal.mdx

+ Add the useAppKitAccount hook to react and next docs
+ Fix all hooks docs

Fix: hooks in all reown AppKit Docs

---

docs/appkit/upgrade/to-reown-appkit-ethers-web.mdx
docs/appkit/upgrade/to-reown-appkit-ethers5-web.mdx
docs/appkit/upgrade/to-reown-appkit-solana-web.mdx
docs/appkit/upgrade/to-reown-appkit-web.mdx

Update upgrade guides
+ Solana
+ Ethers 5
+ Ethers
+ wagmi
https://reown-docs-git-feat-create-solana-ethers-upgrade-reown-com.vercel.app/appkit/upgrade/to-reown-appkit-web

Feat: Update upgrade guides

---

docs/appkit/flutter/core/installation.mdx
docs/appkit/flutter/core/options.mdx
docs/appkit/flutter/core/usage.mdx
docs/appkit/flutter/onboarding/email.mdx
sidebars.js

[Flutter] docs update for social login

---

docs/appkit/shared/options.mdx

Add networks information in shared options

Feat: Add networks information in options

---

docs/appkit/shared/options.mdx
docs/appkit/shared/socials.mdx

Small Fixes on:
- Options 
https://reown-docs-git-feat-small-fixes-options-reown-com.vercel.app/appkit/react/core/options#enablewalletconnect
- Social Logins
https://reown-docs-git-feat-small-fixes-options-reown-com.vercel.app/appkit/react/onboarding/socials

feat: Small fixes options

---

docs/appkit/next/core/hooks.mdx
docs/appkit/react/core/hooks.mdx
docs/appkit/vue/core/composables.mdx

- Update the disconnect hooks section
https://reown-docs-git-feat-update-usedisconnect-hook-reown-com.vercel.app/appkit/react/core/hooks?platform=solana#usedisconnect

feat: Update the disconnect hooks section

---

docs/appkit/javascript/core/actions.mdx

add a solution for modal disconnect in vanillaJS

Fix: solution until modal.disconnect is visible again

---

docs/appkit/shared/siwe/code.mdx

This PR removes an unwanted comment from the SIWE docs page. 

Docs update: Removing unnecessary comment from JS SIWE doc page

---

docs/appkit/next/core/hooks.mdx
docs/appkit/react/core/hooks.mdx
docs/appkit/vue/core/composables.mdx

Refactors hook docs.
- Collect every `useAppKit*` hooks together
- Unify their description
- Add `Returns` and `Parameters` section each for better DevEx
Updated the following hook docs:
- Next/hooks
- React/hooks
- Vue/Composables

refactor: hook docs

---

docs/appkit/shared/theming.mdx
docs/cloud/verify.mdx
docs/walletkit/android/verify.mdx
docs/walletkit/best-practices.mdx
docs/walletkit/c-sharp/verify.mdx
docs/walletkit/flutter/verify.mdx
docs/walletkit/ios/verify.mdx
docs/walletkit/react-native/verify.mdx
docs/walletkit/web/verify.mdx

Blowfish is shutting down soon. Consequently, this PR removes all references to Blowfish from the docs. 

Docs update: Remove all references to Blowfish

---

docs/appkit/upgrade/to-reown-appkit-web.mdx
docs/appkit/vue/core/composables.mdx
docs/appkit/vue/core/installation.mdx
docs/appkit/vue/solana/implementation.mdx
docs/appkit/vue/wagmi/about/implementation.mdx

+ Fix upgrade
https://reown-docs-git-fix-basic-vue-docs-reown-com.vercel.app/appkit/upgrade/to-reown-appkit-web?platform=vue
+ Installation
https://reown-docs-git-fix-basic-vue-docs-reown-com.vercel.app/appkit/vue/core/installation
+ Implementation
https://reown-docs-git-fix-basic-vue-docs-reown-com.vercel.app/appkit/vue/core/installation#implementation
+ Compostables
https://reown-docs-git-fix-basic-vue-docs-reown-com.vercel.app/appkit/vue/core/composables

fix: vue implementation and upgrade

---

docs/appkit/shared/smart-sessions.mdx

Add one step to install the experimental library 
https://reown-docs-git-feat-smart-session-npm-reown-com.vercel.app/appkit/react/experimental/smart-session

Feat: add npm install experimental

---

docs/appkit/flutter/core/custom-chains.mdx
docs/appkit/flutter/core/events.mdx
docs/appkit/flutter/core/installation.mdx
docs/appkit/flutter/core/link-mode.mdx
docs/appkit/flutter/core/options.mdx
docs/appkit/flutter/core/siwe.mdx
docs/appkit/flutter/core/usage.mdx

Update docs to reflect non-EVM support

[Flutter] Non EVM support docs

---

docs/appkit/next/wagmi/hooks.mdx
docs/appkit/react-native/wagmi/hooks.mdx
docs/appkit/react/wagmi/hooks.mdx
docs/appkit/vue/wagmi/about/implementation.mdx

Replace wagmi useAccount by AppKit useAppKitAccount hook

Fix: we recommend using useAppKitAccount, not wagmi  useAccount hook

---

docs/appkit/shared/smart-sessions.mdx

This PR fixes the indentation of the code on Step 5. 

Docs update: Fixing indentation Smart sessions

---

.github/workflows/grammar-check.yml

This PR is to create a workflow that will run a grammar check on every PR made to the docs.

Creating a workflow that automatically runs a grammar check on every PR

---

docs/appkit/shared/siwe/code.mdx

Add info to normalize address in SIWE react
Related: https://github.com/reown-com/web-examples/pull/777
https://reown-docs-git-feat-normalize-address-siwe-react-reown-com.vercel.app/appkit/react/core/siwe#configure-your-siwe-client

Feat: add info to normalize address

---

docs/appkit/vue/core/composables.mdx

+ improve docs for vue compostables
https://reown-docs-git-fix-vue-compostables-reown-com.vercel.app/appkit/vue/core/composables

fix: Vue compostables

---

docs/appkit/next/core/installation.mdx
docs/appkit/overview.mdx
docs/appkit/react/core/installation.mdx
docs/readme.mdx
docs/walletkit/overview.mdx
docusaurus.config.js
sidebars.js

This PR is a first stab at the project to improve the docs further. This PR:
- Makes a few minor changes to the sidebar. 
- Renames "Dashboard" to "Cloud Dashboard" to make it more clear. 
- Links AppKit Lab on the docs' navbar. 
- Renames "Get Started" to "Quickstart". 
- Updates and links AppKit video tutorial to React and Next installation docs. 
- Re-arranges AppKit features according to their importance. 

Docs update: Improving the docs further for better DevEx

---

docs/appkit/features/telegram-mini-apps.mdx

- Delete the libraries not needed anymore
- Add a link to our blog post

Fix/ delete the libraries not needed anymore

---

docs/appkit/react-native/core/installation.mdx
docs/components/GithubBox.js

+ Add links to examples
+ Fix description text for dark mode
https://reown-docs-git-feat-github-link-react-native-reown-com.vercel.app/appkit/react-native/core/installation#examples

Feat/ Add links to examples

---

docs/appkit/flutter/core/options.mdx
docs/appkit/react-native/core/options.mdx
docs/appkit/shared/options.mdx
docs/cloud/wallets/wallet-list.mdx
docs/components/WalletCard.js
docs/components/WalletList.js
sidebars.js

+ Add wallet list in docs
+ https://reown-docs-git-feat-add-wallet-list-reown-com.vercel.app/cloud/wallets/wallet-list
+ Add links to the wallet list
+ https://reown-docs-git-feat-add-wallet-list-reown-com.vercel.app/appkit/vue/core/options#featuredwalletids

Feat/ add wallet list to get Id fast

---

docs/appkit/upgrade/to-reown-appkit-web.mdx

Update upgrade guide to change WagmiConfig x WagmiProvider
https://reown-docs-git-fix-upgrade-wagmi-provider-reown-com.vercel.app/appkit/upgrade/to-reown-appkit-web

Fix: WagmiConfig x WagmiProvider

---

docs/appkit/overview.mdx

The overview page for AppKit was quite minimal in terms of both the description of AppKit and the overview of its features. This PR addresses that. 

Docs Update: Updating AppKit overview doc content

---

.github/pull_request_template.md

This PR creates a simple pull request template.
N/A
N/A

Docs Update: Creating a Pull Request Template 

---

docs/appkit/recipes/telegram-mini-app.mdx

This PR removes unwanted packages from the telegram mini app recipe on the docs. 
Preview not yet deployed

Docs Update: Removing conflicting messaging from a recipe

---

.cspell.json
docs/appkit/shared/smart-sessions.mdx

Add More context in the text of Smart Sessions
https://reown-docs-git-feat-add-more-info-smart-sessions-reown-com.vercel.app/appkit/react/experimental/smart-session

add more context to the initial SS text

---

.github/pull_request_template.md

This PR alters the existing PR template to make it easy to comprehend.
N/A
N/A

Docs Update: Update pull_request_template.md to improve the template

---

docs/appkit/shared/siwe/code.mdx

fix: small typo

---

docs/appkit/vue/wagmi/about/implementation.mdx

Docs: Added a missing closing curly bracket

---

docs/appkit/react/solana/hooks.mdx
docs/appkit/vue/solana/composables.mdx

fix: typo fixs

---

docs/appkit/next/core/hooks.mdx
docs/appkit/react/core/hooks.mdx
docs/appkit/vue/core/composables.mdx

add await to disconnect from the hook
building

fix: add await to disconnect in docs

---

docs/appkit/react-native/core/email.mdx
docs/appkit/react-native/core/options.mdx
docs/appkit/react-native/core/smart-accounts.mdx
docs/appkit/react-native/ethers/email.mdx
docs/appkit/react-native/wagmi/email.mdx
sidebars.js

* Added social login config for react native
* Added link to Smart Accounts page (from web)
* Added new `debug` prop

chore: added new debug prop + social login configs

---

docs/appkit/javascript/core/custom-connectors.mdx
docs/appkit/javascript/core/installation.mdx
docs/appkit/javascript/ethers/actions.mdx
docs/appkit/javascript/solana/about/implementation.mdx
docs/appkit/javascript/solana/about/programs.mdx

clean react mentions in javascript

fix: clean react mentions in javascript

---

docs/appkit/vue/core/composables.mdx

update accountData structure in composables documentation
https://reown-docs-git-fix-hook-appkitaccount-values-reown-com.vercel.app/appkit/vue/core/composables#useappkitaccount

fix: update accountData structure in composables documentation

---

.cspell.json
docs/appkit/features/smart-accounts.mdx
docs/appkit/recipes/switching-to-send-calls.mdx
docs/appkit/shared/smart-accounts.mdx
docs/appkit/shared/sponsored-transactions.mdx

add more info about smart wallets 
https://reown-docs-git-feat-add-info-smart-wallets-reown-com.vercel.app/appkit/features/smart-accounts

feat: add info smart wallets

---

docs/appkit/unity/core/actions.mdx
docs/appkit/unity/core/usage.mdx

- Add EVM Actions docs for Unity APpKit
- Add gas amount estimation to the smart contract interaction example in Unity AppKit usage docs

Add Unity EVM actions docs

---

docs/appkit/recipes/bitcoin-send-transaction.mdx
docs/appkit/recipes/solana-send-transaction.mdx
sidebars.js

- add bitcoin guide
- small fix in solana guide
https://reown-docs-git-feat-add-bitcoin-guide-reown-com.vercel.app/appkit/recipes/bitcoin-send-transaction

feat: add bitcoin guide

---

docs/appkit/recipes/bitcoin-send-transaction.mdx

handle balance functions in guide
https://reown-docs-git-feat-add-bitcoin-guide-reown-com.vercel.app/appkit/recipes/bitcoin-send-transaction

fix: handle balance functions in guide

---

docs/readme.mdx
sidebars.js

- This PR updates the existing highlighted recipes on the homepage of the docs. 
- It also moves the SIWX doc page under "Authentication". 
- https://reown-docs-git-update-recipes-reown-com.vercel.app/

Docs Update: Replacing the highlighted recipes on homepage

---

src/css/custom.css

This PR is to fix the broken view of the feature table on mobile
- https://reown-docs-git-feature-mobile-fix-reown-com.vercel.app/

Docs Fix: Fixing mobile view for the table

---

docs/cloud/paymaster.mdx

Switch beta label to limited access for paymaster.
- https://reown-docs-git-chore-switch-beta-to-lim-reown-com.vercel.app/cloud/paymaster

Cloud Paymaster: switch beta to limited access 

---

docs/appkit/flutter/core/custom-chains.mdx
docs/appkit/flutter/core/email.mdx

Minor changes in Flutter docs

---

docs/appkit/javascript/core/siwe.mdx
docs/appkit/next/core/siwe.mdx
docs/appkit/react/core/siwe.mdx
docs/appkit/shared/siwe/code.mdx

fix siwe signature msg with social logins and emails
- https://reown-docs-git-fix-verify-msg-in-siwe-reown-com.vercel.app/appkit/next/core/siwe
- https://reown-docs-git-fix-verify-msg-in-siwe-reown-com.vercel.app/appkit/react/core/siwe
https://github.com/reown-com/web-examples/pull/801

fix: SIWE signature msg with social logins and emails

---

docs/appkit/flutter/core/custom-chains.mdx
docs/appkit/flutter/core/email.mdx
docs/appkit/flutter/core/link-mode.mdx
docs/appkit/flutter/core/options.mdx
docs/appkit/flutter/core/siwe.mdx

Added configurations examples for AppKit flutter and other minor changes

[Flutter] configurations examples for AppKit

---

docs/appkit/shared/resources.mdx

add more resources

---

docs/appkit/recipes/bitcoin-send-transaction.mdx

Add the function to get the public key in recipe
https://reown-docs-git-chore-improve-bitcoin-recipe-pu-f5ae0b-reown-com.vercel.app/appkit/recipes/bitcoin-send-transaction

Add the function to get the public key in recipe

---

docs/appkit/flutter/core/installation.mdx

Phantom Wallet Support

---

docs/appkit/features/index.mdx
docs/appkit/features/smart-accounts.mdx

This PR updates the feature table for Unity and Flutter. It also updates the supported chains for smart accounts. 
- https://reown-docs-git-feature-fix-reown-com.vercel.app/appkit/features/

Doc Fix: Fixing feature table and updating supported chains for smart accounts

---

docs/appkit/flutter/core/installation.mdx

Added important information in order to integrate Phantom Wallet support.

Add important information about Phantom Wallet

---

docs/appkit/flutter/core/installation.mdx

Minor change in Phantom docs

---

docs/walletkit/ios/usage.mdx

added telemetry for ios

---

docs/appkit/shared/multichain.mdx
docs/components/PlatformTabs.js

Add bitcoint to multichain
https://reown-docs-git-feat-add-bitcoin-to-multichain-reown-com.vercel.app/appkit/react/core/multichain?platform=wagmi+%2B+bitcoin

Feat: add bitcoint to multichain

---

docs/appkit/react-native/core/options.mdx
docs/appkit/react-native/core/theming.mdx
sidebars.js

* Added theming page
* Added swaps prop 
https://reown-docs-git-chore-rn-swaps-theming-reown-com.vercel.app/appkit/react-native/core/options#features
https://reown-docs-git-chore-rn-swaps-theming-reown-com.vercel.app/appkit/react-native/core/theming

chore: added theming and features docs for RN

---

docs/appkit/flutter/core/installation.mdx

Added extra info about Phantom Wallet support
https://reown-docs-git-feature-enhanceflutterphantomdocs-reown-com.vercel.app/appkit/flutter/core/installation#phantom-wallet-support

Added extra info about Phantom Wallet support

---

docs/walletkit/features/experimental/chain-abstraction.mdx

added video for chain abstraction

---

docs/appkit/react-native/core/hooks.mdx

* added useAppKitEventSubscription hook for react native
https://reown-docs-git-chore-rn-hooks-reown-com.vercel.app/appkit/react-native/core/hooks#useappkiteventsubscription

chore: RN - added useAppKitEventSubscription hook

---

docs/appkit/javascript/core/installation.mdx
docs/appkit/javascript/solana/about/programs.mdx

fix code for vanillaJS to call smart Contracts or transfers
https://reown-docs-git-chore-fix-vanillajs-code-reown-com.vercel.app/appkit/javascript/core/installation#blockchain-interaction

fix: code for vanillaJS to call smart Contracts or transfers

---

docs/advanced/security/content-security-policy.md

See [Slack conversation](https://reown-inc.slack.com/archives/C03RVH94K5K/p1738093950773889?thread_ts=1737656831.626119&cid=C03RVH94K5K)

chore: add cdn.zerion.io to CSP

---

docs/appkit/react-native/core/options.mdx
docs/appkit/shared/options.mdx

delete tokens options as it is not working

fix: delete tokens options as it is not working

---

docs/appkit/recipes/sponsoring-first-transaction.mdx

- Add basic trouble shooting to the paymaster recipe
https://reown-docs-git-paymaster-troubleshooting-guide-reown-com.vercel.app/appkit/recipes/sponsoring-first-transaction#troubleshooting

chore: trouble shooting guide

---

docs/walletkit/android/experimental/chain-abstraction.mdx
docs/walletkit/features/experimental/chain-abstraction.mdx
docs/walletkit/ios/experimental/chain-abstraction.mdx
docs/walletkit/react-native/experimental/chain-abstraction.mdx

added USDT support for chain abstraction

---

docs/appkit/recipes/EVM-smart-contract-interaction.mdx
sidebars.js

Add recipe to interact with a smart contract
https://reown-docs-git-feat-add-smart-contract-interac-280a9a-reown-com.vercel.app/appkit/recipes/EVM-smart-contract-interaction

Feat: add recipe to interact with a smart contract

---

docs/appkit/javascript/transactions/onramp.mdx
docs/appkit/next/transactions/onramp.mdx
docs/appkit/react/transactions/onramp.mdx
docs/appkit/vue/transactions/onramp.mdx

* React: https://reown-docs-git-feat-onrampapi-reown-com.vercel.app/appkit/react/transactions/onramp#on-ramp-api
* Vue: https://reown-docs-git-feat-onrampapi-reown-com.vercel.app/appkit/vue/transactions/onramp#on-ramp-api
* JS: https://reown-docs-git-feat-onrampapi-reown-com.vercel.app/appkit/javascript/transactions/onramp#on-ramp-api
* Next: https://reown-docs-git-feat-onrampapi-reown-com.vercel.app/appkit/next/transactions/onramp#on-ramp-api

feat(onramp): explain onramp api

---

docs/appkit/javascript/core/actions.mdx
docs/appkit/next/core/open.mdx
docs/appkit/react/core/open.mdx
docs/appkit/vue/core/open.mdx
docs/cloud/blockchain-api.mdx

This PR fixes a few minor grammatical issues with the onramp hook mentioned across AppKit docs (in Web).
-

Docs fix: Minor grammatical fixes under Onramp hook

---

docs/appkit/upgrade/wcm.mdx

create a new PR from this one -> https://github.com/reown-com/reown-docs/pull/296

Small changes to WCM preview

---

docs/appkit/shared/theming.mdx

fix: delete berapong

---

docs/appkit/flutter/core/actions.mdx
docs/appkit/flutter/core/custom-chains.mdx
docs/appkit/flutter/core/installation.mdx
docs/appkit/flutter/core/options.mdx
docs/appkit/flutter/core/usage.mdx

https://reown-docs-git-flutter-updates-reown-com.vercel.app/appkit/flutter/core/installation
https://reown-docs-git-flutter-updates-reown-com.vercel.app/appkit/flutter/core/usage
https://reown-docs-git-flutter-updates-reown-com.vercel.app/appkit/flutter/core/options
https://reown-docs-git-flutter-updates-reown-com.vercel.app/appkit/flutter/core/actions
https://reown-docs-git-flutter-updates-reown-com.vercel.app/appkit/flutter/core/custom-chains

Minor flutter docs update

---

docs/appkit/react-native/core/components.mdx
docs/appkit/shared/components.mdx
docs/web3modal/v2/_partials/themeVariablesTable.mdx
docs/web3modal/v2/_partials/wcModalThemeVariablesTable.mdx

Adds `namespace` parameter to AppKit Button component.

feat: add namespace param to appkit button

---

scripts/build-llmstxt.js

* Fix the `/llms.txt` blockquote summary to match company tagline
* Followup to #309

fix: llms.txt summary/tagline

---

.cspell.json
docs/appkit/migration/from-rainbowkit-next.mdx

fix migration from rainbowkit guide

chore:  fix migration from rainbowkit guide

---

docusaurus.config.js
src/theme/Navbar/Search/index.js

Updating Algolia config to display the library/framework/language with each search result.

Docs Update: Fixing search to display library

---

.cspell.json
docs/appkit/next/core/components.mdx
docs/appkit/next/core/hooks.mdx
docs/appkit/react/core/components.mdx
docs/appkit/react/core/hooks.mdx

Add all supported wallets to the component and hook
https://reown-docs-git-chore-add-supported-wallets-in-buttons-reown-com.vercel.app/appkit/react/core/components#options-for-wallet-property

feat: Add all supported wallets to the component and hook

---

docs/appkit/javascript/solana/about/implementation.mdx
docs/appkit/next/solana/about/implementation.mdx
docs/appkit/react/core/installation.mdx
docs/appkit/react/solana/about/implementation.mdx
docs/appkit/react/solana/implementation.mdx
docs/appkit/shared/multichain.mdx
docs/appkit/upgrade/from-w3m-to-reown.mdx
docs/appkit/upgrade/to-reown-appkit-solana-web.mdx
docs/appkit/vue/core/installation.mdx
docs/appkit/vue/solana/about/implementation.mdx
docs/appkit/vue/solana/implementation.mdx

Delete custom wallet in Solana from default config

Delete custom wallet from default config

---

sidebars.js

Fix project as it was not working

fix : delete link to wallet in sidebar

---

docs.json

fix: Update docs.json to fix favicon

---

docs.json

Update docs.json to fix favicon

---

.github/pull_request_template.md
README.md
appkit/authentication/socials.mdx
package-lock.json
package.json

1. This PR creates and adds a README.md file that showcases how a user can clone the docs and test it locally. It also has a brief set of steps to walk people through the process of opening a PR or contributing to the docs. 
2. This PR also fixes a minor title formatting issue on the social login docs. 
NA

chore: Creating a README.md file and fixing some other minor issues

---

snippets/appkit/shared/options.mdx

chore: add enableNetworkSwitch docs

---

snippets/appkit/shared/options.mdx

chore: add universalProviderConfigOverride docs

---

appkit/flutter/core/installation.mdx

Added small note to highlight reown cli usage
PREVIEW_URL_1

[Flutter] Added small note to highlight reown cli usage

---

appkit/react-native/core/installation.mdx
appkit/react/core/installation.mdx
appkit/react/core/siwe.mdx
snippets/appkit/shared/siwx/siwx-default.mdx

fix Github boxes that where having some errors or without the github logo

fix: Github boxes

---

advanced/api/sign/dapp-usage.mdx
advanced/api/sign/wallet-usage.mdx
advanced/walletconnectmodal/usage.mdx
appkit/ios/core/usage.mdx
walletkit/ios/notifications/notify/usage.mdx
walletkit/ios/usage.mdx
walletkit/web/usage.mdx

This PR fixes some of the overdue broken links due to a structural change in the docs.

fix: Fixing broken links

---

overview.mdx

feat: improve learn more

---

walletkit/features/verify.mdx

There is a minor formatting issue on the current doc page for Verify API. This PR fixes that and also adds a screenshot of what the userflow would look like.

Fix: Fixing Verify API doc page

---

appkit/react-native/core/installation.mdx
appkit/react-native/core/link-mode.mdx
appkit/react-native/core/siwe.mdx
appkit/recipes/travel-rule.mdx
appkit/upgrade/appkitv2.mdx
appkit/upgrade/from-web3modal-android.mdx
appkit/upgrade/from-web3modal-flutter.mdx
appkit/upgrade/from-web3modal-ios.mdx
appkit/upgrade/from-web3modal-react-native.mdx
appkit/upgrade/from-web3modal-unity.mdx
docs.json
snippets/appkit/javascript/ethers/about/triggermodal.mdx
snippets/appkit/javascript/solana/about/triggermodal.mdx
snippets/appkit/javascript/wagmi/about/implementation.mdx
snippets/appkit/javascript/wagmi/about/triggermodal.mdx
snippets/appkit/next/wagmi/about/implementation.mdx
snippets/appkit/react-native/ethers/email.mdx
snippets/appkit/react-native/wagmi/email.mdx
snippets/appkit/react/wagmi/about/implementation.mdx
snippets/appkit/shared/onramp.mdx
snippets/appkit/shared/options.mdx
snippets/appkit/shared/siwx/siwx-cloud-auth.mdx
snippets/appkit/shared/siwx/siwx-default.mdx
snippets/appkit/shared/socials.mdx
snippets/appkit/shared/swaps.mdx
snippets/appkit/vue/wagmi/about/implementation.mdx
walletkit/flutter/link-mode.mdx
walletkit/ios/link-mode.mdx

This PR updates existing code snippets on 28 different files with incorrect/faulty code highlighting with a fix.

Fix: Fixing some overdue code highlight issues

---

appkit/recipes/telegram-mini-app.mdx
appkit/recipes/tenderly-virtual-testnets.mdx
appkit/upgrade/from-w3m-to-reown.mdx
appkit/upgrade/from-web3modal-android.mdx
appkit/upgrade/from-web3modal-flutter.mdx
appkit/upgrade/from-web3modal-ios.mdx
appkit/upgrade/from-web3modal-react-native.mdx
appkit/upgrade/from-web3modal-unity.mdx
appkit/upgrade/to-reown-appkit-ethers-web.mdx
appkit/upgrade/to-reown-appkit-ethers5-web.mdx
appkit/upgrade/to-reown-appkit-solana-web.mdx
appkit/upgrade/to-reown-appkit-web.mdx
docs.json
overview.mdx
walletkit/upgrade/from-web3wallet-android.mdx
walletkit/upgrade/from-web3wallet-flutter.mdx
walletkit/upgrade/from-web3wallet-ios.mdx
walletkit/upgrade/from-web3wallet-react-native.mdx
walletkit/upgrade/from-web3wallet-to-reown.mdx
walletkit/upgrade/from-web3wallet-unity.mdx
walletkit/upgrade/from-web3wallet-web.mdx

This PR restructures the sidebar and the general navigation of the docs.

Docs Update: Revamping navbar and sidebar

---

docs.json

This PR fixes some of the missing sections in the docs.

fix: Pushing fix for missing sections in the docs

---

appkit/upgrade/to-reown-appkit-ethers-web.mdx
appkit/upgrade/to-reown-appkit-ethers5-web.mdx
appkit/upgrade/to-reown-appkit-solana-web.mdx

This PR does the following: 
1. Updates the `.mdx` files that has incorrect code highlighting. 
2. Updates the AppKit Solana upgrade guide which was broken and had poor code formatting all over.

fix: Fix highlight issue on several doc pages

---

walletkit/android/early-access/chain-abstraction.mdx

chore: update kotlin CA docs

---

appkit/upgrade/from-web3modal-unity.mdx
appkit/upgrade/to-reown-appkit-web.mdx

This PR removes some poorly formatted highlighted code for a fix.

fix: Updating highlighted code for a fix

---

walletkit/android/link-mode.mdx
walletkit/flutter/link-mode.mdx
walletkit/ios/link-mode.mdx
walletkit/react-native/link-mode.mdx

added info about 1CA for link mode

---

appkit/javascript/core/actions.mdx
snippets/appkit/next/core/open.mdx
snippets/appkit/react/core/open.mdx
snippets/appkit/vue/core/open.mdx

chore: add open swap with arguments docs

---

.cspell.json
snippets/appkit/shared/smart-sessions.mdx
walletkit/features/chain-abstraction.mdx

Feat: Modify smart session one page

---

appkit/next/core/hooks.mdx
appkit/react/core/hooks.mdx

This PR adds more context and use-cases to React and Next's hooks docs.

Docs Update: Adding more context to React and Next's hooks docs

---

appkit/javascript/core/actions.mdx

Add wallet buttons to VanillaJS

Add wallet buttons to VanillaJS

---

appkit/unity/core/actions.mdx
appkit/unity/core/installation.mdx

- Add direct wallet connection docs to Unity appkit
- Fix minor mistakes in installation docs of Unity appkit

chore: unity appkit update

---

docs.json
overview.mdx

This PR updates the company description as per the Tone of Voice document shared by the Marketing team. This PR also adds the missing Discord server invite to the footer.

Docs Update: Updating company desc as per Tone of Voice

---

appkit/features/chain-abstraction.mdx
walletkit/features/chain-abstraction.mdx

This PR updates the networks and assets supported for Chain Abstraction.

Docs Update: Update networks and assets supported for Chain Abstraction

---

appkit/recipes/smart-sessions.mdx

fix: typo error in SS

---

.cspell.json
docs.json
walletkit/features/link-mode.mdx

This PR adds Link Mode to WalletKit features.

Adding Link Mode to WalletKit features

---

walletkit/flutter/usage.mdx

Just a better explanation in some sections of Flutter WalletKit

[Flutter] Documentation enhancement

---

snippets/appkit/shared/theming.mdx

delete wormfare example page in themes as it's not working

Fix/ delete wormfare

---

appkit/flutter/core/email.mdx
appkit/payments/pay-with-exchange.mdx

This PR fixes the grammatical issues on AppKit Pay docs.

Docs Update: Minor grammar fix on AppKit Pay docs

---

.cspell.json
appkit/javascript/payments/pay-with-exchange.mdx
appkit/payments/pay-with-exchange.mdx
snippets/appkit/shared/appkit-pay-react.mdx

Update snippets for appkit Pay

feat: Update snippets for appkit Pay

---

snippets/appkit/shared/appkit-pay-react.mdx

fix link appkit pay

---

appkit/flutter/core/actions.mdx
appkit/flutter/core/custom-chains.mdx
appkit/flutter/core/email.mdx
appkit/flutter/core/installation.mdx
appkit/flutter/core/options.mdx
appkit/flutter/core/usage.mdx

Flutter docs update specially after new Social Login implementation with web-wallet
Just a refresh of the documentation based on newest changes in the Flutter SDK

Flutter docs update

---

appkit/migration/from-anza-adapter-react.mdx
appkit/recipes/solana-send-transaction.mdx

- migration from anza solana
- small typo fix in Solana guide

Fix: migration from anza solana

---

snippets/appkit/shared/smart-accounts.mdx

Fix: upgrade smart account support networks

Fix: upgrade smart account support networks

---

advanced/multichain/rpc-reference/near-rpc.mdx
walletkit/flutter/chain-abstraction.mdx
walletkit/flutter/installation.mdx

Important updates on Flutter WalletKit

Important updates on Flutter WalletKit

---

walletkit/upgrade/staying-up-to-date.mdx

Docs Update: Fixing typo

---

snippets/appkit/shared/options.mdx

Feat: add to the medata info

---

walletkit/android/eip5792.mdx
walletkit/flutter/eip5792.mdx
walletkit/ios/eip5792.mdx
walletkit/react-native/eip5792.mdx
walletkit/web/eip5792.mdx

chore: update 5792 docs with batchId format

---

appkit/upgrade/wcm.mdx

add "other networks" to wcm migration

feat: add other networks to wcm migration

---

appkit/payments/pay-with-exchange.mdx

This PR adds FAQs for AppKit Pay.

Docs Update: Adding AppKit FAQs

---

snippets/appkit/shared/options.mdx

more specific to the use of the option

---

appkit/migration/from-connectkit-next.mdx
appkit/migration/from-privy-next.mdx
appkit/migration/from-rainbowkit-next.mdx
docs.json
snippets/appkit/shared/resources.mdx

migration guide Privy to reown

Feat: migration guide Privy to reown

---

appkit/overview.mdx
appkit/paid-plans/enterprise.mdx
docs.json
reown-appkit.mdc

This PR creates a dedicated enterprise page on the Docs. 
- [Preview Link 1](https://reown-5552f0bb-enterprise.mintlify.app/appkit/paid-plans/enterprise)

Docs Update: Creating an Enterprise page

---

appkit/faq.mdx

add error codes and actions for AppKit
-  https://reown-5552f0bb-feat-add-errors-code.mintlify.app/appkit/faq#error-codes

feat: add error codes and actions for AppKit

---

docs.json

This PR removes Web3Inbox and Notifications from the sidebar of AppKit and WalletKit's navigation flows. 

Docs Update: Remove Web3inbox and Notifications from AppKit and WalletKit

---

appkit/unity/core/actions.mdx
appkit/unity/core/usage.mdx

Added notes about Solidity types on native platforms and about direct social login connection

chore: update unity docs

---

walletkit/android/resources.mdx
walletkit/ios/resources.mdx
walletkit/react-native/resources.mdx
walletkit/web/resources.mdx

fix: delete broken links from wallets

fix: delete broken links

---

appkit/javascript/core/custom-networks.mdx
appkit/next/core/custom-networks.mdx
appkit/react/core/custom-networks.mdx
appkit/vue/core/custom-networks.mdx

add customRPCurls to custom network

fix: add customRPCurls to custom network

---

appkit/javascript/core/installation.mdx
appkit/next/core/installation.mdx
appkit/react/core/installation.mdx
snippets/appkit/javascript/core/about/implementation.mdx
snippets/appkit/javascript/core/about/triggermodal.mdx
snippets/appkit/react/core/about/implementation.mdx
snippets/appkit/react/core/about/triggermodal.mdx

AppKit Core with Universal Connector
- React ok
- Next ok 
- Javascript ok
- https://reown-5552f0bb-feat-add-universal-connector.mintlify.app/appkit/javascript/core/installation#others-networks-appkit-core-2
- https://reown-5552f0bb-feat-add-universal-connector.mintlify.app/appkit/react/core/installation#others-networks-appkit-core

AppKit Core with Universal Connector

---

docs.json

Adding open in Perplexity, MCP, Cursor and VSCode to the docs. 

Docs Update: Adding AI improvement for Perplexity, MCP, Cursor and VSCode

---

appkit/faq.mdx

add 2 faqs

---

snippets/appkit/next/wagmi/about/implementation.mdx

fix: async fn

---

appkit/flutter/core/installation.mdx
appkit/flutter/core/link-mode.mdx
appkit/flutter/core/usage.mdx
appkit/react-native/core/link-mode.mdx

Remove "Cloud Configuration" reference from Link Mode sections on AppKit side

Link Mode docs enhancements

---

docs.json

delete paymaster from the sidebar
- home

fix: delete paymaster from the sidebar
