reown-com/reown-docs

- docs/appkit/flutter/core/custom-chains.mdx
- Changing `suppoted` to `supported` to fix grammar. 
- Fixing a broken link.
> Docs update: Fix grammar and broken link

- docs/appkit/migration/from-rainbowkit-next.mdx
Fix a spelling error at step no 4 where
onst wagmiAdapter = new WagmiAdapter({
ssr: true,
networks,
projectId
})
into 
const wagmiAdapter = new WagmiAdapter({
ssr: true,
networks,
projectId
})
> Fix typo/spelling mistake in doc - rainbowkit migration

- docs/appkit/react/core/installation.mdx
A lot of users set up their React app by running `npx create-react-app` command and this causes dependency issues as this command has been deprecated. This PR adds a cautionary message stating the same and asking users to use Vite to set up their React app. 
> Docs update: Adding a warning message for create-react-app

- docs/appkit/react/core/installation.mdx
Users have to install @solana/wallet-adapter-wallets separately, instead the docs should have instructions to install it too.
> Installation command missing instructions for Solana adapter wallets 

- docs/appkit/upgrade/to-reown-appkit-web.mdx
+ Add more info for vue
+ Add some small updates suggested from Cali
+ Fix some text using v6
+ Fix some typos
> chore: Improve upgrade guide

- docs/appkit/next/core/installation.mdx
Installation guide for Next must have installation instruction for @solana/wallet-adapter-wallets as users have to install manually. For completeness, we should have it in the guide.
> Missing instruction in installation guide

- docs/appkit/migration/from-connectkit-next.mdx
- docs/appkit/migration/from-rainbowkit-next.mdx
- sidebars.js
The existing migration guide we have on the docs to move from RainbowKit is outdated as it shows users how they can move from that to Web3Modal instead. This PR addresses that issue by updating the migration guide to Reown's AppKit
This PR also adds a migration guide to move from ConnectKit to AppKit to the docs. 
> Docs update: Updating RainbowKit migration guides for Reown AppKit

- docs/appkit/features/socials.mdx
`AppKit v1.1.0` uses all the chains available in the `viem/chains` package under the hood. These chains can be used out of the box by importing them from `@reown/appkit/networks`. As part of this release, the social and email login features of AppKit are now supported with all EVM chains listed in the `viem/chains` package.
This PR updates the existing information on supported chains for social and email login to reflect the latest changes.
> Docs update: Updating supported chains info for social and email login feature

- docs/appkit/features/telegram-mini-apps.mdx
- sidebars.js
Reown's AppKit now supports Telegram Mini apps right out of the box. This PR creates a simple doc page that contains general info about this feature and the packages that a developer needs to install before they proceed with setting up AppKit. 
Tested locally with Docusauras.
> Docs update: Creating the doc page for telegram mini apps

- docs/walletkit/web/usage.mdx
- Was pointed out to me that these links are 404'ing
- The internal pkg has been moved out to its own repo so GH can't redirect automatically.
> fix(walletkit): fix broken links to integration test examples

- docs/appkit/shared/theming.mdx
The current theming docs lacks examples of existing Web3 apps that have a fully customized integration of AppKit. This PR addresses that. 
> Docs update: updating theming docs to showcase examples

- docs/advanced/multichain/rpc-reference/bitcoin-rpc.md
- docs/advanced/multichain/rpc-reference/dogecoin-rpc.md
- docs/advanced/multichain/rpc-reference/litecoin-rpc.md
- Most current implementations implicitly associate `broadcast = true` to mean `finalize = true`.
- This is stated for example in the `sats-connect` docs: https://docs.xverse.app/sats-connect/bitcoin-methods/signpsbt
- Update the wording of the optional `broadcast` param on the `signPsbt` method to make this expected relationship explicit.
> chore(rpc): explicit note finalization on `broadcast` param

- docs/appkit/next/core/hooks.mdx
- docs/appkit/react/core/hooks.mdx
- docs/appkit/shared/options.mdx
- docs/appkit/vue/core/composables.mdx
+ Remove addNetworks from useAppKitNetwork
+ Remove allowunsupportedchain
https://reown-docs-git-fix-remove-addnetwork-from-usea-b35ce4-reown-com.vercel.app/appkit/next/core/hooks#useappkitnetwork
https://reown-docs-git-fix-remove-addnetwork-from-usea-b35ce4-reown-com.vercel.app/appkit/vue/core/composables
close -> https://github.com/reown-com/appkit/issues/3192
> Fix: remove addNetworks & allowunsupportedchain

- docs/advanced/walletconnectmodal/options.mdx
- docs/api/notify/usage.mdx
- docs/appkit/android/core/options.mdx
- docs/appkit/flutter/core/options.mdx
- docs/appkit/ios/core/options.mdx
- docs/appkit/react-native/core/options.mdx
- docs/appkit/shared/options.mdx
- docs/appkit/unity/core/options.mdx
- docs/cloud/chains/chain-list.mdx
- docs/cloud/explorer-submission.mdx
- docs/cloud/explorer.md
- docs/walletkit/ios/mobile-linking.mdx
- docs/web3modal/v2/_partials/customisation/customExplorerWallets.mdx
- docs/web3modal/v2/_partials/customisation/customManualWallets.mdx
- docs/web3modal/v2/_partials/customisation/customWagmiWalletsIntro.mdx
- docs/web3modal/v2/_partials/options/enableExplorer.mdx
- docs/web3modal/v2/_partials/options/explorerExcludedWalletIds.mdx
- docs/web3modal/v2/_partials/options/explorerRecommendedWalletIds.mdx
- docs/web3modal/v2/_partials/options/projectId.mdx
- docs/web3modal/v2/_partials/options/walletImages.mdx
WalletConnect Explorer is being renamed as WalletGuide. This PR replaces all references to "WalletConnect Explorer" with "WalletGuide". 
**Do not merge until November 10, 2024**
> Docs Update: Replacing all references to WalletConnect Explorer with WalletGuide

- docs/appkit/shared/theming.mdx
- Add two web examples in theme section
https://reown-docs-git-feat-add-theme-examples-reown-com.vercel.app/appkit/react/core/theming
> Feat: add two web examples for theming

- docs/appkit/shared/siwe/code.mdx
fixed minor syntax errors for the SIWE example and made the `siweConfig` object exported
> fix docs for js SIWE example

- docs/walletkit/android/mobile-linking.mdx
- docs/walletkit/best-practices.mdx
- docs/walletkit/flutter/mobile-linking.mdx
- docs/walletkit/ios/mobile-linking.mdx
- docs/walletkit/react-native/mobile-linking.mdx
This PR addresses an issue reported by @skibitsky and @jakubuid with wallets redirecting to the QR code instead of the dapp. Linear ticket [here](https://linear.app/reown/issue/DR-346/clarify-wallet-redirect-behavior-in-documentation-for-qr-code-scanning)
> Docs Update: Updating Mobile linking docs to address a redirect edge case

- docs/appkit/react-native/core/installation.mdx
The current docs do not link to the React Native monorepo where developers can report issues. This PR addresses that. 
> Docs update: Adding a "Getting support" section with React Native monorepo

- docs/appkit/shared/chain-abstraction.mdx
Removing the `__mode` requirement and adding a note to use latest wagmi as of now.
> chore: update ca docs

- docs/appkit/recipes/telegram-mini-app.mdx
- docs/appkit/recipes/tenderly-virtual-testnets.mdx
- package-lock.json
This PR adds a Github box for the github repo linked within each of the recipes. 
- https://reown-docs-o2jgmd2b4-reown-com.vercel.app/appkit/recipes/tenderly-virtual-testnets#conclusion
- https://reown-docs-o2jgmd2b4-reown-com.vercel.app/appkit/recipes/telegram-mini-app#configure-the-telegram-mini-app-with-reown-appkit
> Docs Update: Adding Github boxes for the repo URLs for each recipe

- docs/appkit/next/wagmi/about/implementation.mdx
The error occurs because the headers() function from next/headers returns a ```Promise<ReadonlyHeaders>```, not the ```ReadonlyHeaders``` object directly. 
Correction:
You need to ```await``` the ```headers()``` call to retrieve the actual headers object.
Without awaiting the headers() call:
With awaiting the headers() call:
> headers() function from next/headers returns a Promise<ReadonlyHeaders>

- docs/appkit/recipes/solana-send-transaction.mdx
- docusaurus.config.js
- sidebars.js
This PR updates the AppKit Demo button to point to the new Reown AppKit Demo instead of AppKit Lab. This PR also fixes a minor issue with a recipe showing up on the sidebar and corrects the grammar of the title for the recipe. 
- https://reown-docs-git-change-demo-reown-com.vercel.app/
- https://reown-docs-git-change-demo-reown-com.vercel.app/appkit/recipes/solana-send-transaction
> Docs Update: Replacing the demo URL and fixing a recipe

- docs/appkit/next/wagmi/about/implementation.mdx
Remove unecessary parentheses after headersObj when accessing the cookie using next headers. The correct syntax is headersObj.get('cookie') as headersObj is an object, not a function.
Corrects code example syntax in headers documentation.
[https://reown-docs-git-fork-matsfjeldstad-remove-unnec-c446c2-reown-com.vercel.app/](https://reown-docs-git-fork-matsfjeldstad-remove-unnec-c446c2-reown-com.vercel.app/)
> fix: Remove unnecessary parentheses in header cookie access

- docs/appkit/javascript/solana/about/programs.mdx
- docs/appkit/next/solana/about/programs.mdx
- docs/appkit/react/solana/about/programs.mdx
- docs/appkit/vue/solana/programs.mdx
change Url for a working example in solana
https://reown-docs-git-fix-old-links-solana-reown-com.vercel.app/appkit/react/core/installation?platform=solana
> fix: url for a working example in Solana

- docs/appkit/next/core/components.mdx
- docs/appkit/next/core/hooks.mdx
- docs/appkit/next/core/theming.mdx
- docs/appkit/react/core/components.mdx
- docs/appkit/react/core/hooks.mdx
- docs/appkit/react/core/theming.mdx
Add link and image to wallet buttons
- https://reown-docs-git-feat-add-image-and-link-to-wallet-reown-com.vercel.app/appkit/react/core/hooks#useappkitwallet
- https://reown-docs-git-feat-add-image-and-link-to-wallet-reown-com.vercel.app/appkit/react/core/components#appkit-wallet-button--
- https://reown-docs-git-feat-add-image-and-link-to-wallet-reown-com.vercel.app/appkit/react/core/theming#wallet-buttons
> feat: Add link and image to wallet buttons

- docs/appkit/features/siwx/default.mdx
- docs/appkit/shared/siwx/index.mdx
- sidebars.js
Adds a more user-friendly name to the SIWX title/sidebar.
> chore(siwx): add authentication name to SIWX

- src/css/custom.css
There was a minor css issue that broke how the recipe container appeared on light mode. This PR fixes that.
- https://reown-docs-git-fix-theme-reown-com.vercel.app/
> Docs Fix: Fixing broken light mode display for Recipe container

- docs/appkit/features/index.mdx
- docusaurus.config.js
This PR fixes a type on the Features doc page and also fixes the docs defaulting to the user's device's default theme.
- https://reown-docs-git-fix-docs-reown-com.vercel.app/
> Docs Fix: Fixing typo and removing device default theme being enforced

- docs/appkit/javascript/core/siwe.mdx
- docs/appkit/next/core/siwe.mdx
- docs/appkit/react/core/siwe.mdx
Add reference to 1271 and 6492 in SIWE
https://reown-docs-git-chore-add-eip-signature-to-siwe-reown-com.vercel.app/appkit/react/core/siwe#one-click-auth
> Add reference to 1271 and 6492

- docs/appkit/android/core/installation.mdx
- docs/appkit/flutter/core/installation.mdx
- docs/appkit/ios/core/installation.mdx
- docs/appkit/react-native/core/installation.mdx
Add all the links to test dApps
- https://reown-docs-git-chore-add-link-to-test-dapps-reown-com.vercel.app/appkit/react-native/core/installation
- https://reown-docs-git-chore-add-link-to-test-dapps-reown-com.vercel.app/appkit/flutter/core/installation
- https://reown-docs-git-chore-add-link-to-test-dapps-reown-com.vercel.app/appkit/android/core/installation
- https://reown-docs-git-chore-add-link-to-test-dapps-reown-com.vercel.app/appkit/ios/core/installation
> Add all the links to test dApps

- docs/appkit/react-native/ethers/about/coinbase.mdx
- docs/appkit/react-native/ethers5/about/coinbase.mdx
- docs/appkit/react-native/wagmi/about/coinbase.mdx
* Added a note for devs to prefer using universal-links over custom schemes in Coinbase integration
https://reown-docs-git-chore-coinbase-link-reown-com.vercel.app/appkit/react-native/core/installation#enable-coinbase-wallet
> chore: added coinbase universal link note for RN

- docs/appkit/javascript/core/installation.mdx
- docs/appkit/next/core/installation.mdx
- docs/appkit/react/core/installation.mdx
- docs/appkit/vue/core/installation.mdx
This PR adds the steps to use the AppKit CLI to set up AppKit and install the necessary packages. This PR adds it to the installation doc page for React, Next and Vue. 
- [React](https://reown-docs-git-add-cli-reown-com.vercel.app/appkit/react/core/installation#installation)
- [Next.js](https://reown-docs-git-add-cli-reown-com.vercel.app/appkit/next/core/installation#installation)
- [Vue](https://reown-docs-git-add-cli-reown-com.vercel.app/appkit/vue/core/installation#installation)
> Adding steps to use CLI for React, Next and Vue

- docs/components/CloudBanner.js
The current configuration of the cloud banner uses Plausible to track clicks and other analytics. Since we no longer use Plausible, this PR removes that config and substitutes it with a utm_source instead. This will allow us to track analytics via Google Analytics. 
- https://reown-docs-git-cloud-click-analytics-reown-com.vercel.app/appkit/react/core/installation#cloud-configuration
> fix: Removing Plausible and adding a utm_source for the Cloud banner

- docs/appkit/shared/notifications/frontend-integration/api/managing-subscription/react.mdx
- docs/appkit/shared/siwx/siwx-custom.mdx
- docs/walletkit/ios/experimental/chain-abstraction.mdx
> chore: fix some typos in comment

- docs/appkit/javascript/ethers/about/triggermodal.mdx
In the deployed docs the ["ethers actions" example](https://docs.reown.com/appkit/javascript/core/installation?platform=ethers) threw me off, so I thought I'd just raise a quick PR for it.
- Moved the highlighting to the buttons that are to be added, and,
- removed the web-components from the markup
Umm, so bit of a bummer here actually I couldn't run this repo locally and have raised an issue for it so cannot check both the things below, you can check out the issue [here](https://github.com/reown-com/reown-docs/issues/248) btw.
Umm, not sure if I can even trigger a preview XD
Oh and also, there wasn't any `Contributing.md` so I just raised the PR for `main`, lmk if there are any changes to be made to the branch or the PR, would be glad to do so.
P.S. Love the project, and happy to help! …
> DOCS: fix javascript trigger modal action example

- docs/appkit/upgrade/wcm.mdx
- sidebars.js
This PR creates a consolidated upgrade guide on Web to move from WalletConnect Modal to AppKit Basic. It covers Ethereum Provider, Universal Provider and Sign Client as well. The PR also has examples to each web library/programming language that developers can refer to. 
- https://reown-docs-git-wcm-upgrade-reown-com.vercel.app/appkit/upgrade/wcm
> Docs Update: Adding Upgrade guide to move from WalletConnect Modal to AppKit Basic

- sidebars.js
This PR is to hide the WCM upgrade guide temporarily until AppKit Core is deployed. 
- https://reown-docs-git-hide-wcm-upgrade-reown-com.vercel.app/
> Docs Update: Hiding wcm upgrade guide temporarily

- .github/workflows/algolia-reindex.yml
- docusaurus.config.js
- Use updated Algolia appId and search apiKey with fresh index
- Sets up GHA to auto reindex the site when there is a change to `docs/**` on `main`
https://reown-docs-git-feat-algolia-auto-reindex-reown-com.vercel.app/
> chore(config): update algolia appId, auto-recrawl via GHA

- docs/cloud/blockchain-api.mdx
This PR updates the current Blockchain API limits mentioned in the docs for free tier. 
- https://reown-docs-git-rpc-limits-reown-com.vercel.app/cloud/blockchain-api
> Docs Update: Updating Blockchain API limits for the free tier of AppKit

- docs/appkit/overview.mdx
This PR updates the the AppKit demo link on AppKit overview doc page.
- https://reown-docs-git-fix-appkit-demo-reown-com.vercel.app/appkit/overview
> Docs update: Replacing the AppKit demo on AppKit overview doc

- docs/appkit/next/core/components.mdx
- docs/appkit/next/core/installation.mdx
- docs/appkit/react/core/components.mdx
- docs/appkit/react/core/installation.mdx
feat: remove v19 warning
https://reown-docs-git-feat-remove-react-v19-warn-reown-com.vercel.app/appkit/next/core/installation#trigger-the-modal
> feat: remove v19 warning

- docs/appkit/next/core/hooks.mdx
- docs/appkit/react/core/hooks.mdx
- docs/appkit/vue/core/composables.mdx
add namespace to useAppKitAccount Hook
https://reown-docs-git-chore-add-useappkitaccount-name-7e28e2-reown-com.vercel.app/appkit/react/core/hooks#useappkitaccount
> Feat: add namespace to useAppKitAccount Hook

- .gitignore
- package.json
- pnpm-lock.yaml
- scripts/README.md
- scripts/build-llmstxt.js
- scripts/package.json
This PR implements support for the [LLMSTXT specification](https://llmstxt.org/) by generating two standardized text files (`llms.txt` and `llms-full.txt`) from our Docusaurus documentation. These files make our documentation more accessible to Large Language Models (LLMs) and other AI tools.
- Added a new script (`scripts/build-llmstxt.js`) that converts Docusaurus markdown files to LLMSTXT format
- The script generates two files:
- `llms.txt`: An index file with links to all documentation sections, organized by directory and platform
- `llms-full.txt`: A comprehensive file containing all documentation content
- Added progress tracking and error handling for processing large numbers of files
- The script recursively processes all markdown and MDX files in the docs directory
- The script …
> feat: sets up llms.txt and llms-full.txt

- docs/appkit/react-native/core/options.mdx
Added new prop to override connector images
https://reown-docs-git-chore-rn-connector-images-reown-com.vercel.app/appkit/react-native/core/options#connectorimages
> chore: added connectorImages prop to AppKit RN

- sidebars.js
Change title of the guide in sidebar for Gas Sponsorship in two places
https://reown-docs-git-feat-change-guide-title-sponsor-tx-reown-com.vercel.app/
> feat: change title of the guide in sidebar

- docs.json
- Fix casing in sidebar/nav: `Appkit` -> `AppKit`
> fix: standardize capitalization in AppKit dropdowns

- docs.json
Mintlify launched a new feature to enable a contextual menu for every page of the docs. This allows readers to copy and view a given doc page as markdown. It also allows them to open the doc page in ChatGPT and Claude to ask questions. 
More info about the feature can be found [here](https://mintlify.com/docs/core-concepts/ai-ingestion#contextual-menu). 
This PR adds the `contextual` param to the `docs.json` file for this purpose.
> Docs Update: Adding contextual copy and open options to the docs

- appkit/upgrade/wcm.mdx
- docs.json
This PR does the following:
1. Adds AppKit Core upgrade guide to the sidebar.
2. Removes AppKit Core set up from the upgrade doc. 
3. Adds a note that for projects that have `@walletconnect/modal` to remove it and refer to the Universal Provider path to set up AppKit Core/WalletConnect.
4. Adds a brief paragraph about the docs page that devs should refer to if they are looking to set up AppKit Core from scratch.
5. Removes code snippet for Ethereum Provider and highlights that developers using this do not need to take any action.
> Docs Update: Final improvements to AppKit Core upgrade doc

- walletkit/android/eip5792.mdx
- walletkit/flutter/eip5792.mdx
- walletkit/ios/eip5792.mdx
- walletkit/react-native/eip5792.mdx
- walletkit/web/eip5792.mdx
This PR adds examples on how 5792 capabilities can be defined in CAIP-25 handshake and how wallet should respond to such request
> feat: caip-25 example for 5792 capabilities

- appkit/features/smart-sessions.mdx
This PR renames "Smart Sessions" to "Automated Onchain Actions" and also adds info about the networks supported.
> Docs Update: Renaming "Smart Sessions" in the docs and adding more context

- appkit/recipes/EVM-smart-contract-interaction.mdx
- appkit/recipes/bitcoin-send-transaction.mdx
- appkit/recipes/ethers-send-transaction.mdx
- appkit/recipes/solana-send-transaction.mdx
The docs have several occurences of usage of `useAppKitProvider` without brackets, which just doesn't work (not a function call). This PR fixes them (or at least some of them, since github.dev has limited search capabilities).
> docs: call useAppKitProvider correctly

- appkit/android/core/one-click-auth.mdx
- appkit/flutter/core/siwe.mdx
- appkit/ios/core/one-click-auth.mdx
- appkit/javascript/core/siwe.mdx
- appkit/networks/bitcoin.mdx
- appkit/networks/solana.mdx
- appkit/next/core/siwe.mdx
- appkit/payments/one-click-checkout.mdx
- appkit/react-native/core/siwe.mdx
- appkit/react/core/siwe.mdx
- appkit/unity/core/siwe.mdx
- appkit/unity/core/socials.mdx
- appkit/vue/core/siwe.mdx
- docs.json
This PR does the following:
1. Updates the redirect links for network specific AppKit installation docs to be handled correctly for Bitcoin and Solana
2. Adds "Authentication" section to all of the AppKit's technical docs. 
3. Updates inconsistent sidebar title for One Click Auth.
4. Adds info about how wallets should support `wallet_checkout` for one-click checkout to work.
> Docs Update: Fixing network specific links and other improvements

- advanced/multichain/rpc-reference/sui-rpc.mdx
This PR creates a file for Sui RPC methods and adds some of the core RPC methods for Sui to the doc page.
> Docs Update: Adding Sui RPC methods to the docs

- advanced/multichain/rpc-reference/bitcoin-rpc.mdx
- advanced/multichain/rpc-reference/stacks-rpc.mdx
- advanced/multichain/rpc-reference/sui-rpc.mdx
- Adds recommendation to serialize responses to `sui_getAccounts`, `stacks_getAddresses` and `bip122_getAccountAddresses` in `sessionProperties` 
> feat: add btc, sui and stacks accounts caching to RPC specs

- docs.json
This PR updates the AppKit sidebar to rename "Android" to Kotlin and "iOS" to "Swift". 
- [Preview Link 1](https://reown-5552f0bb-sidebar-rename.mintlify.app/appkit/overview)
> Docs Update: Updating `Android` to `Kotlin` and `iOS` to `Swift` in the sidebar
